routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Livewire\Usuarios;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::middleware(['auth:sanctum', 'verified'])
	->get('/usuarios', Usuarios::class)
	->name('usuarios');

Route::middleware(['auth:sanctum', 'verified'])->get('/productos', function () {
    return view('dashboard');
})->name('productos');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;
use DateTime;
class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
		'password',
		'documento',
		'genero',
		'fecha_nacimiento',
		'telefono',
		'eps_id',
		'rol_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
	];

	public function eps()
    {
        return $this->hasOne('App\Models\tbEps', 'id',  'eps_id');
	}

	public function rol()
    {
        return $this->hasOne('App\Models\tbRoles', 'id',  'rol_id');
	}

	public function getEdadAttribute()
	{
		$date1 = new DateTime($this->fecha_nacimiento);
		$date2 = new DateTime("now");
		$diff = $date1->diff($date2);


		return $diff->y;
	}
}

app/Http/Livewire/ModuloCategorias.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Livewire\WithPagination;
//MODELS
use App\Models\Categorias;

class ModuloCategorias extends Component
{

	use WithPagination;

	public $search;
	public $perPage = '5';
	public $ifOpenModalCategorias = false;
	public $ifOpenDeleteCategorias = false;
	public $categoriasInput = Categorias::class;
	public $create = true; // edit = false

	protected $rules = [
		'categoriasInput.id_padre'=>'nullable|exists:categorias,id',
		'categoriasInput.nombre' => 'required|max:200',
	];
	protected $messages = [
		'id.exists' => 'El id debe existir en la tabla de categorias.',
		'required' => 'El campo :attribute es requerido.',
		'numeric' => 'El campo :attribute debe ser un numero',
		'unique' => 'El :attribute :input ya existe en la tabla de categorias.',
		'max' => 'El :attribute no debe tener más de :max caracteres.'
	];

    public function render()
    {
		$categorias = Categorias::where('nombre', 'like', "%{$this->search}%")
			->orWhere('id_padre', 'like', "%{$this->search}%")
			->with('padre');
        return view('livewire.categorias.categoriasView', [
			'categorias' => $categorias->paginate($this->perPage),
			'padres' => Categorias::get()
		]);
	}

	public function createCategoria()
	{
		$this->validate();
		Categorias::create($this->categoriasInput);
		$this->categoriasInput = Categorias::class;
		$this->ifOpenModalCategorias = false;
		$this->notify('Categoria creada con exito');
	}

	public function updateCategoria()
	{
		$this->validate();
		$this->categoriasInput->save();
		$this->categoriasInput = Categorias::class;
		$this->ifOpenModalCategorias = false;
		$this->notify('Categoria actualizada con exito');
	}

	public function deleteCategoria()
	{
		$this->categoriasInput->delete();
		$this->categoriasInput = Categorias::class;
		$this->ifOpenDeleteCategorias = false;
		$this->notify('Categoria eliminada con exito');
	}

	public function showCreateCategoria()
	{
		$this->ifOpenModalCategorias = true;
		$this->categoriasInput = Categorias::class;
		$this->create = true;
	}

	public function showEditCategoria(Categorias $categoria)
    {
		$this->categoriasInput = $categoria;
		$this->ifOpenModalCategorias = true;
		$this->create = false;
	}

	public function showDeleteCategoria(Categorias $categoria)
	{
		$this->categoriasInput = $categoria;
		$this->ifOpenDeleteCategorias = true;
	}

	public function closeModalsCategoria()
	{
		$this->ifOpenModalCategorias = false;
		$this->ifOpenDeleteCategorias = false;
	}

}

app/Http/Livewire/Usuarios.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\User;
use App\Models\tbEps;
use App\Models\tbRoles;
use Illuminate\Support\Facades\Hash;

use DateTime;

class Usuarios extends Component
{

	public $usuario = User::class;
	public $ifOpenModalUsuarios = false;
	public $ifOpenDeleteUsuario = false;
	public $create;

	protected $rules = [
        'usuario.name' => 'required',
		'usuario.email' => 'required|email',
		// 'usuario.password' => 'required',
		'usuario.documento' => 'required',
		'usuario.genero' => 'required',
		'usuario.fecha_nacimiento' => 'required',
		'usuario.telefono' => 'required',
		'usuario.eps_id' => 'required',
		'usuario.rol_id' => 'required',
    ];

    public function render()
    {
        return view('livewire.usuarios', [
			'usuarios' => User::with(['eps','rol'])->get(),
			'roles' => tbRoles::get(),
			'eps' => tbEps::get(),
		]);
	}

	public function showCreateUsuarios()
	{
		$this->usuario = User::class;
		$this->ifOpenModalUsuarios = true;
		$this->create = true;
	}

	public function closeModalsUsuarios()
	{
		$this->ifOpenModalUsuarios = false;
	}

	public function createUsuarios()
	{
		$this->validate();
		$password = Hash::make($this->usuario['password']);
		$this->usuario['password'] = $password;
		User::create($this->usuario);
		$this->ifOpenModalUsuarios = false;
		$this->notify('Usuario creado con exito');
	}

	public function showEditUsuario(User $usuario)
	{
		$this->usuario = $usuario;
		$this->ifOpenModalUsuarios = true;
		$this->create = false;
	}

	public function updateUsuarios()
	{
		$usuario = User::whereId($this->usuario['id'])->first();
		if($usuario->password != $this->usuario['password']){
			$password = Hash::make($this->usuario['password']);
			$this->usuario['password'] = $password;
		}else{
			$this->usuario['password'] = $usuario->password;
		}
		$this->usuario->save();
		$this->ifOpenModalUsuarios = false;
		$this->notify('Usuario actualizado con exito');
	}

	public function showDeleteUsuario(User $usuario)
	{
		$this->ifOpenDeleteUsuario = true;
		$this->usuario = $usuario;
	}

	public function closeModalsUsuario()
	{
		$this->ifOpenDeleteUsuario = false;
		$this->ifOpenModalUsuarios = false;
	}

	public function deleteUsuario()
	{
		$this->usuario->delete();
		$this->closeModalsUsuario();
		$this->notify('Usuario eliminado con exito');
	}
}

resources/views/livewire/usuarios.blade.php
<div class="p-5">

	<div class="max-w-7xl mx-auto sm:px-6 lg:px-8 py-2">
		<x-jet-button wire:click="showCreateUsuarios">
			{{ __('Crear usuarios') }}
		</x-jet-button>
	</div>

	@include('livewire.usuariosForm')

	<x-modal.confirmation wire:model="ifOpenDeleteUsuario" maxWidth="sm" class="h-5/6">

		<x-slot name="title">
			¿Desea eliminar este usuario?
		</x-slot>

		<x-slot name="content">
			Este proceso no se podrá revertir!
		</x-slot>

		<x-slot name="footer">

			<x-button.danger wire:click="closeModalsUsuario">
				{{ __('Cancelar') }}
			</x-button.danger>

			<x-button.primary wire:click='deleteUsuario' class="ml-4" wire:loading.attr="disabled">
				{{ __('Borrar Usuario') }}
			</x-button.primary>

		</x-slot>

	</x-modal.confirmation>

	<!-- This example requires Tailwind CSS v2.0+ -->
	<div class="flex flex-col">
		<div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
		<div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
			<div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
			<table class="min-w-full divide-y divide-gray-200">
				<thead class="bg-gray-50">
				<tr>
					<th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
					Nombre
					</th>
					<th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
					Documento
					</th>
					<th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
					ROL
					</th>
					<th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
					EPS
					</th>
					<th scope="col" class="relative px-6 py-3">
					</th>
				</tr>
				</thead>
				<tbody class="bg-white divide-y divide-gray-200">

					@foreach ($usuarios as $usuario)

					@if ($usuario->edad > 50)
						<tr class="bg-red-200">
					@elseif ($usuario->edad < 18)
						<tr class="bg-green-200">
					@else
						<tr>
					@endif

							<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
								{{ $usuario->name }}
							</td>
							<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
								{{ $usuario->documento }}
							</td>
							<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
								{{ $usuario->rol->nombre }}
							</td>
							<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
								{{ $usuario->eps->nombre }}
							</td>
							<td class="px-6 py-4 text-right text-sm font-medium">
								<x-button.link wire:click="showEditUsuario({{ $usuario->id }})">
									Editar
								</x-button.link>
								<x-button.link wire:click="showDeleteUsuario({{ $usuario->id }})" class="text-red-500 ml-3">
									Eliminar
								</x-button.link>
							</td>
						</tr>

					@endforeach

				<!-- More people... -->
				</tbody>
			</table>
			</div>
		</div>
		</div>
	</div>
</div>

resources/views/livewire/usuariosForm.blade.php
<x-jet-dialog-modal wire:model="ifOpenModalUsuarios">

	<x-slot name="title">
		@if ($create)
			Crear usuario
		@else
			Editar usuario
		@endif
	</x-slot>


	<x-slot name="content">

		@if (session()->has('message'))
			<div class="alert alert-success">
				{{ session('message') }}
			</div>
		@endif

			<div>
				<x-jet-label for="rol" value="{{ __('Rol') }}" />
				<select wire:model="usuario.rol_id" id="rol_id" name="rol_id" class="mt-1 block border border-gray-300 bg-white rounded-md text-gray-500 w-full">
					<option value="">Seleccionar</option>
					@foreach($roles as $rol)
						<option value="{{ $rol->id }}">{{ $rol->nombre }}</option>
					@endforeach
				</select>
				@error('usuario.rol_id') <span class="error text-red-600">{{ $message }}</span> @enderror
			</div>

			<div class="mt-2">
				<x-jet-label for="eps" value="{{ __('Eps') }}" />
				<select wire:model="usuario.eps_id" id="eps_id" name="eps_id" class="mt-1 block border border-gray-300 bg-white rounded-md text-gray-500 w-full">
					<option value="">Seleccionar</option>
					@foreach($eps as $ep)
						<option value="{{ $ep->id }}">{{ $ep->nombre }}</option>
					@endforeach
				</select>
				@error('usuario.eps_id') <span class="error text-red-600">{{ $message }}</span> @enderror
			</div>

			<div class="mt-2">
				<x-jet-label for="nombre" value="{{ __('Nombre') }}" />
				<x-jet-input wire:model="usuario.name" id="name" name="name" class="block text-gray-500 mt-1 w-full" type="text" />
				@error('usuario.name') <span class="error text-red-600">{{ $message }}</span> @enderror
			</div>

			<div class="mt-2">
				<x-jet-label for="email" value="{{ __('Email') }}" />
				<x-jet-input wire:model="usuario.email" id="email" name="email" class="block text-gray-500 mt-1 w-full" type="text" />
				@error('usuario.email') <span class="error text-red-600">{{ $message }}</span> @enderror
			</div>

			<div class="mt-2">
				<x-jet-label for="password" value="{{ __('Password') }}" />
				<x-jet-input wire:model="usuario.password" id="password" name="password" class="block text-gray-500 mt-1 w-full" type="text" />
				@error('usuario.password') <span class="error text-red-600">{{ $message }}</span> @enderror
			</div>

			<div class="mt-2">
				<x-jet-label for="documento" value="{{ __('Documento') }}" />
				<x-jet-input wire:model="usuario.documento" id="name" name="name" class="block text-gray-500 mt-1 w-full" type="text" />
				@error('usuario.documento') <span class="error text-red-600">{{ $message }}</span> @enderror
			</div>

			<div class="mt-2">
				<x-jet-label for="genero" value="{{ __('Genero') }}" />
				<select wire:model="usuario.genero" id="genero" name="genero" class="mt-1 block border border-gray-300 bg-white rounded-md text-gray-500 w-full">
					<option value="">Seleccionar</option>
					<option value="masculino">Masculino</option>
					<option value="femenino">Femenino</option>
				</select>
				@error('usuario.genero') <span class="error text-red-600">{{ $message }}</span> @enderror
			</div>

			<div class="mt-2">
				<x-jet-label for="fecha_nacimiento" value="{{ __('Fecha nacimiento') }}" />
				<x-jet-input wire:model="usuario.fecha_nacimiento" id="fecha_nacimiento" name="fecha_nacimiento" class="block text-gray-500 mt-1 w-full" type="text" />
				@error('usuario.fecha_nacimiento') <span class="error text-red-600">{{ $message }}</span> @enderror
			</div>

			<div class="mt-2">
				<x-jet-label for="telefono" value="{{ __('Telefono') }}" />
				<x-jet-input wire:model="usuario.telefono" id="telefono" name="telefono" class="block text-gray-500 mt-1 w-full" type="text" />
				@error('usuario.telefono') <span class="error text-red-600">{{ $message }}</span> @enderror
			</div>

	</x-slot>

	<x-slot name="footer">

		<x-jet-danger-button wire:click="closeModalsUsuarios">
			{{ __('Cancelar') }}
		</x-jet-danger-button>

		<x-button.primary wire:click='createUsuarios' class="ml-4" wire:loading.attr="disabled" hidden="{{!$create}}">
			{{ __('Crear usuario') }}
		</x-button.primary>

		<x-button.primary wire:click='updateUsuarios' class="ml-4" wire:loading.attr="disabled" hidden="{{$create}}">
			{{ __('Editar usuario') }}
		</x-button.primary>

	</x-slot>

</x-jet-dialog-modal>